### ISSUE TITLE
CropTransformation.java sometimes  crashes

### ISSUE THREAD

**Issue by artemkutukov** [wasabeef/picasso-transformations#25]
```
Fatal Exception: java.lang.RuntimeException
Transformation CropTransformation(width=600, height=451, mWidthRatio=0.0, mHeightRatio=0.0, mAspectRatio=1.33, gravityHorizontal=CENTER, mGravityVertical=TOP) crashed with exception.

Caused by java.lang.NullPointerException
android.graphics.Canvas. (Canvas.java:136)
jp.wasabeef.picasso.transformations.CropTransformation.transform (CropTransformation.java:301)
com.squareup.picasso.BitmapHunter.applyCustomTransformations (BitmapHunter.java:429)
com.squareup.picasso.BitmapHunter.hunt (BitmapHunter.java:238)
com.squareup.picasso.BitmapHunter.run (BitmapHunter.java:159)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:422)
java.lang.Thread.run (Thread.java:848)
com.squareup.picasso.Utils$PicassoThread.run (Utils.java:411)
```

**Comment by DenK91** [comment]
The same issue is reproduced on Blur case:
Fatal Exception: java.lang.RuntimeException: Transformation BlurTransformation(radius=25, sampling=1) crashed with exception.
       at com.squareup.picasso.BitmapHunter$3.run(BitmapHunter.java:434)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5292)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at android.graphics.Canvas.<init>(Canvas.java:136)
       at ru.newsmediamobile.babo.prototype.utils.image.BlurTransformation.transform(BlurTransformation.java:48)
       at com.squareup.picasso.BitmapHunter.applyCustomTransformations(BitmapHunter.java:429)
       at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:238)
       at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
       at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

**Comment by vahid-m** [comment]
we have the same issue.
